### PR TITLE
replace . with - in docker labels

### PR DESCRIPTION
**Pull request by wallies**
First attempt at Go, seems to work. Not real sure this is the best way though.

### CODE REVIEW

**Comment by digital-wonderland** [comment]
Thanks for the request. I guess it makes ones life easier if one can't control the format of the labels for some reason while doing no harm so I'm totally fine with it.

However, to keep things consistent, I guess it then should also happen for ```container.Node.Labels``` (~10 lines bellow your change). Could you do the same there and then squash those two commits into one?

**Comment by cookandy** [comment]
I manually updated my `config.go` with the change @wallies made (plus the change @digital-wonderland  mentioned ~10 lines below).  However, I'm still getting errors in elasticsearch:

```
 MapperParsingException[Field name [docker/label/com.docker.compose.config-hash] cannot contain '.']
```

**Comment by cookandy** [comment]
Opened issue https://github.com/digital-wonderland/docker-logstash-forwarder/issues/26 to track

**Comment by cookandy** [comment]
Question:  how is `config.go` used?  I can't find anywhere in the Dockerfile which references it.

**Comment by digital-wonderland** [comment]
@wallies Thanks a lot for your work!

@cookandy you must have been doing something wrong since the code works ;P ```config.go``` is not referenced in the Dockerfile since it is Go code which gets compiled into the docker-logstash-forwarder binary.

**Pull request merged**
